### ISSUE TITLE
create_r_baseimage.py do not build the cointaner correctly

### ISSUE THREAD

**Issue by pinduzera** [sassoftware/open-model-manager-resources#6]
I have been trying using that code but it starts building the container but never finshes it, the name and tag in the docker image list it kept stuck as <none> about 300MB without going further.

**Comment by hxin19** [comment]
Are you able to create Python base image?
R base image generation requires extra packages to be downloaded. Make sure that you have enough available space in the host where Docker daemon is running.

**Comment by pinduzera** [comment]
The python worked flawlessly.

Yes, I do have plenty of space. It's a localhost registry/daemon
/dev/sda3       299G  198G  102G  66%

I could build it using an r-base from docker hub directly from bash, is it the same file?

Just tried again, this is how the container kept stuck using this code.
```

REPOSITORY                              TAG                 IMAGE ID            CREATED             SIZE
<none>                                  <none>              fed2b93076b7        2 minutes ago      394MB

```

**Comment by hxin19** [comment]
I doubt it is due to centos version. When the Viya 3.5 was developed and released, the centos latest version was 7.0. Our base images were  based on centos:latest. So we didn’t notice any problem in the testing that time. Now the latest centos is 8.0. It may cause issue downloading some R dependency packages. Here is the workaround:

**First**, login into the machine where Docker daemon is being installed;
**Second**, Execute
     **docker image rm centos:latest**
to remove centos:latest from local cache;
**Last**, run the following two commands to pull down ‘centos:7 image’ and tag it as ‘centos:latest’
   **docker pull centos:7**
  **docker tag centos:7 centos:latest**

Then restart your base image generation script.

**Comment by pinduzera** [comment]
Now it got stucked in even earlier stage of the container, but I don't know if it makes any difference. 203MB

**Comment by pinduzera** [comment]
Yeah, didn't work. 20 minutes building and got to 491MB, little more than before.
Even though this time there is a container running which i think it's the centos, before it wouldn't show at all.

Edit: Looks like after 30 minutes it was built.
